language: android

jdk:
 - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:

  - echo "sdk.dir=$ANDROID_HOME" > local.properties

script:
  - ./gradlew clean check -PdisablePreDex

cache:
  directories:
    - $HOME/.gradle
