language: android

jdk:
 - oraclejdk7
 - openjdk7

android:
  components:
    - platform-tools
    - tools
    - android-22
    - build-tools-22.0.1
    - extra-google-m2repository
    - extra-android-m2repository

before_install:

  - echo "sdk.dir=$ANDROID_HOME" > local.properties

script:
   - ./gradlew assembleDebug -PdisablePreDex
   - ./gradlew lint checkstyle findbugs pmd -PdisablePreDex

cache:
  directories:
    - $HOME/.gradle
